# Generated by Django 2.0.5 on 2018-05-16 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180516_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.Cart'),
        ),
    ]
