# Generated by Django 2.0.5 on 2018-05-16 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180516_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
